// src/utils/classData.js

const classData = [
  {
    id: 1,
    className: "1st Class - A",
    subject: "Mathematics",
    maulana: "Ahmed Khan",
    tags: ["Boys"],
    description: "Basic arithmetic and number sense.",
  },
  {
    id: 2,
    className: "1st Class - B",
    subject: "Science",
    maulana: "Fatima Ali",
    tags: ["Girls"],
    description: "Introduction to plants and animals.",
  },
  {
    id: 3,
    className: "2nd Class - A",
    subject: "Quran",
    maulana: "Mohammed Usman ",
    tags: ["Boys", "Girls", "Adult"],
    description: "Recitation and memorization of short Surahs.",
  },
  {
    id: 4,
    className: "2nd Class - B",
    subject: "History",
    maulana: "Ayesha Noor",
    tags: ["Girls"],
    description: "Stories of early civilizations.",
  },
  {
    id: 5,
    className: "3rd Class - C",    
    subject: "English",
    maulana: "Bilal Shaikh",
    tags: ["Boys"],
    description: "Basic grammar and sentence formation.",
  },
  {
    id: 6,
    className: "3rd Class - D",
    subject: "Quran",
    maulana: "Hafsa Rahman",
    tags: ["Girls", "Adult"],
    description: "Tajweed rules and recitation practice.",
  },
  {
    id: 7,
    className: "4th Class - A",
    subject: "Mathematics",
    maulana: "Imran Siddiqui",
    tags: ["Boys"],
    description: "Multiplication, division, and fractions.",
  },
  {
    id: 8,
    className: "4th Class - B",
    subject: "Science",
    maulana: "Nida Perveen",
    tags: ["Girls"],
    description: "Human body and basic physics.",
  },
  {
    id: 9,
    className: "5th Class - A",
    subject: "Islamic Studies",
    maulana: "Yusuf Patel",
    tags: ["Boys"],
    description: "Fiqh basics and Islamic history.",
  },
  {
    id: 10,
    className: "5th Class - B",
    subject: "Geography",
    maulana: "Sana Khan",
    tags: ["Girls"],
    description: "Maps, continents, and oceans.",
  },
  {
    id: 11,
    className: "6th Class - C",
    subject: "Arabic",
    maulana: "Khalid Hussain",
    tags: ["Child"],
    description: "Arabic alphabets and basic vocabulary.",
  },
  {
    id: 12,
    className: "6th Class - D",
    subject: "Computer Science",
    maulana: "Sara Ahmed",
    tags: ["Girls"],
    description: "Introduction to computers and typing.",
  },
  {
    id: 13,
    className: "7th Class - A",
    subject: "Quran",
    maulana: "Abdul Rahman",
    tags: ["Boys", "Child"],
    description: "Memorization of longer Surahs.",
  },
  {
    id: 14,
    className: "7th Class - B",
    subject: "English Literature",
    maulana: "Maryam Fatima",
    tags: ["Girls"],
    description: "Short stories and comprehension.",
  },
  {
    id: 15,
    className: "8th Class - A",
    subject: "Mathematics",
    maulana: "Omar Farooq",
    tags: ["Girls" , "Boys", "Adult"],
    description: "Algebra, geometry, and equations.",
  },
];

export default classData;
