const customer = [
  {
    id: 1,
    schoolName: "Greenwood High School",
    admin: "Alice Johnson",
    email: "alice.johnson@greenwood.edu",
    contact: "+1 123-456-7890",
    plan: "Premium",
    expiryDate: "2025-12-31",
    status: "Active",
  },
  {
    id: 2,
    schoolName: "Sunnydale Academy",
    admin: "Bob Smith",
    email: "bob.smith@sunnydale.edu",
    contact: "+1 987-654-3210",
    plan: "Basic",
    expiryDate: "2024-06-30",
    status: "Inactive",
  },
  {
    id: 3,
    schoolName: "Riverbank School",
    admin: "Carol Williams",
    email: "carol.williams@riverbank.edu",
    contact: "+1 555-123-4567",
    plan: "Standard",
    expiryDate: "2025-03-15",
    status: "Active",
  },
  {
    id: 4,
    schoolName: "Hillside Prep",
    admin: "David Brown",
    email: "david.brown@hillside.edu",
    contact: "+1 444-987-6543",
    plan: "Premium",
    expiryDate: "2024-11-20",
    status: "Active",
  },
  {
    id: 5,
    schoolName: "Lakeside Institute",
    admin: "Eva Green",
    email: "eva.green@lakeside.edu",
    contact: "+1 333-456-7890",
    plan: "Basic",
    expiryDate: "2024-08-10",
    status: "Inactive",
  },
  {
    id: 6,
    schoolName: "Maple Leaf School",
    admin: "Frank Miller",
    email: "frank.miller@mapleleaf.edu",
    contact: "+1 222-555-6789",
    plan: "Standard",
    expiryDate: "2025-01-05",
    status: "Active",
  },
  {
    id: 7,
    schoolName: "Oakwood Academy",
    admin: "Grace Lee",
    email: "grace.lee@oakwood.edu",
    contact: "+1 111-222-3333",
    plan: "Premium",
    expiryDate: "2024-09-30",
    status: "Active",
  },
  {
    id: 8,
    schoolName: "Pinecrest High",
    admin: "Henry Adams",
    email: "henry.adams@pinecrest.edu",
    contact: "+1 666-777-8888",
    plan: "Basic",
    expiryDate: "2025-02-28",
    status: "Inactive",
  },
  {
    id: 9,
    schoolName: "Cedar Grove School",
    admin: "Ivy Wilson",
    email: "ivy.wilson@cedargrove.edu",
    contact: "+1 999-888-7777",
    plan: "Standard",
    expiryDate: "2025-07-15",
    status: "Active",
  },
  {
    id: 10,
    schoolName: "Evergreen Academy",
    admin: "Jack Thompson",
    email: "jack.thompson@evergreen.edu",
    contact: "+1 555-444-3333",
    plan: "Premium",
    expiryDate: "2024-12-31",
    status: "Active",
  },
  {
    id: 11,
    schoolName: "Brookfield High",
    admin: "Karen Scott",
    email: "karen.scott@brookfield.edu",
    contact: "+1 111-333-5555",
    plan: "Basic",
    expiryDate: "2024-05-20",
    status: "Inactive",
  },
  {
    id: 12,
    schoolName: "Riverside Prep",
    admin: "Leo Martinez",
    email: "leo.martinez@riverside.edu",
    contact: "+1 444-555-6666",
    plan: "Standard",
    expiryDate: "2025-03-10",
    status: "Active",
  },
  {
    id: 13,
    schoolName: "Silver Oak School",
    admin: "Mia Clark",
    email: "mia.clark@silveroak.edu",
    contact: "+1 777-888-9999",
    plan: "Premium",
    expiryDate: "2025-09-25",
    status: "Active",
  },
  {
    id: 14,
    schoolName: "Hilltop Academy",
    admin: "Nathan Young",
    email: "nathan.young@hilltop.edu",
    contact: "+1 222-333-4444",
    plan: "Basic",
    expiryDate: "2024-11-15",
    status: "Inactive",
  },
  {
    id: 15,
    schoolName: "Willow Creek School",
    admin: "Olivia Perez",
    email: "olivia.perez@willowcreek.edu",
    contact: "+1 555-666-7777",
    plan: "Standard",
    expiryDate: "2025-06-30",
    status: "Active",
  },
  {
    id: 16,
    schoolName: "Crestwood High",
    admin: "Paul White",
    email: "paul.white@crestwood.edu",
    contact: "+1 333-444-5555",
    plan: "Premium",
    expiryDate: "2024-10-10",
    status: "Active",
  },
  {
    id: 17,
    schoolName: "Meadowbrook School",
    admin: "Quinn Harris",
    email: "quinn.harris@meadowbrook.edu",
    contact: "+1 888-999-0000",
    plan: "Basic",
    expiryDate: "2025-01-20",
    status: "Inactive",
  },
  {
    id: 18,
    schoolName: "Oakridge Academy",
    admin: "Rachel Lewis",
    email: "rachel.lewis@oakridge.edu",
    contact: "+1 666-555-4444",
    plan: "Standard",
    expiryDate: "2025-08-05",
    status: "Active",
  },
  {
    id: 19,
    schoolName: "Pinehill School",
    admin: "Samuel King",
    email: "samuel.king@pinehill.edu",
    contact: "+1 777-666-5555",
    plan: "Premium",
    expiryDate: "2024-12-20",
    status: "Active",
  },
  {
    id: 20,
    schoolName: "Maple Ridge Academy",
    admin: "Tina Brooks",
    email: "tina.brooks@mapleridge.edu",
    contact: "+1 999-555-3333",
    plan: "Basic",
    expiryDate: "2025-04-15",
    status: "Inactive",
  },
];

export default customer;