// utils/staffData.js
const staffData = [
  {
    name: "Rahul Sharma",
    roll: "ST001",
    department: "Mathematics",
    baseSalary: 30000,
    totalSalary: 35000,
    paymentStatus: "Paid",
  },
  {
    name: "Anita Mehta",
    roll: "ST002",
    department: "Science",
    baseSalary: 28000,
    totalSalary: 32000,
    paymentStatus: "Pending",
  },
  {
    name: "Vikram Singh",
    roll: "ST003",
    department: "English",
    baseSalary: 27000,
    totalSalary: 30000,
    paymentStatus: "Paid",
  },
  {
    name: "Priya Verma",
    roll: "ST004",
    department: "Mathematics",
    baseSalary: 32000,
    totalSalary: 37000,
    paymentStatus: "Pending",
  },
  {
    name: "Ravi Kumar",
    roll: "ST005",
    department: "History",
    baseSalary: 25000,
    totalSalary: 28000,
    paymentStatus: "Paid",
  },
  {
    name: "Sunita Joshi",
    roll: "ST006",
    department: "Science",
    baseSalary: 31000,
    totalSalary: 36000,
    paymentStatus: "Pending",
  },
  {
    name: "Amit Desai",
    roll: "ST007",
    department: "Computer Science",
    baseSalary: 35000,
    totalSalary: 40000,
    paymentStatus: "Paid",
  },
  {
    name: "Neha Kapoor",
    roll: "ST008",
    department: "English",
    baseSalary: 29000,
    totalSalary: 33000,
    paymentStatus: "Paid",
  },
  {
    name: "Karan Malhotra",
    roll: "ST009",
    department: "Physical Education",
    baseSalary: 22000,
    totalSalary: 25000,
    paymentStatus: "Pending",
  },
  {
    name: "Shreya Nair",
    roll: "ST010",
    department: "Biology",
    baseSalary: 28000,
    totalSalary: 32000,
    paymentStatus: "Paid",
  },
  {
    name: "Deepak Yadav",
    roll: "ST011",
    department: "Chemistry",
    baseSalary: 30000,
    totalSalary: 34000,
    paymentStatus: "Pending",
  },
  {
    name: "Meera Iyer",
    roll: "ST012",
    department: "Geography",
    baseSalary: 26000,
    totalSalary: 29000,
    paymentStatus: "Paid",
  },
];

export default staffData;
