// utils/studentData.js

const students = [
  {
    grNo: "101",
    name: "Jacob Jones",
    rollNo: "S270101",
    class: "Class 1",
    section: "Section A",
    gender: "Male",
    status: "Active",
    dateOfJoin: "1 Jan, 2020",
    dob: "8 Sep, 2014",
  },
  {
    grNo: "102",
    name: "Courtney Henry",
    rollNo: "S270102",
    class: "Class 2",
    section: "Section B",
    gender: "Female",
    status: "Inactive",
    dateOfJoin: "15 Feb, 2020",
    dob: "22 Oct, 2013",
  },
  {
    grNo: "103",
    name: "Marvin McKinney",
    rollNo: "S270103",
    class: "Class 3",
    section: "Section C",
    gender: "Male",
    status: "Active",
    dateOfJoin: "10 Mar, 2020",
    dob: "24 May, 2012",
  },
  {
    grNo: "104",
    name: "Eleanor Pena",
    rollNo: "S270104",
    class: "Class 4",
    section: "Section A",
    gender: "Female",
    status: "Active",
    dateOfJoin: "5 Apr, 2020",
    dob: "19 Jul, 2013",
  },
  {
    grNo: "105",
    name: "Theresa Webb",
    rollNo: "S270105",
    class: "Class 5",
    section: "Section B",
    gender: "Female",
    status: "Inactive",
    dateOfJoin: "12 May, 2020",
    dob: "10 Dec, 2012",
  },
  {
    grNo: "106",
    name: "Ralph Edwards",
    rollNo: "S270106",
    class: "Class 6",
    section: "Section C",
    gender: "Male",
    status: "Active",
    dateOfJoin: "20 Jun, 2020",
    dob: "4 Feb, 2011",
  },
  {
    grNo: "107",
    name: "Arlene McCoy",
    rollNo: "S270107",
    class: "Class 7",
    section: "Section A",
    gender: "Female",
    status: "Active",
    dateOfJoin: "11 Jul, 2020",
    dob: "16 Aug, 2010",
  },
  {
    grNo: "108",
    name: "Cody Fisher",
    rollNo: "S270108",
    class: "Class 8",
    section: "Section B",
    gender: "Male",
    status: "Inactive",
    dateOfJoin: "8 Aug, 2020",
    dob: "28 Apr, 2009",
  },
  {
    grNo: "109",
    name: "Dianne Russell",
    rollNo: "S270109",
    class: "Class 9",
    section: "Section C",
    gender: "Female",
    status: "Active",
    dateOfJoin: "23 Sep, 2020",
    dob: "30 Jan, 2008",
  },
  {
    grNo: "110",
    name: "Guy Hawkins",
    rollNo: "S270110",
    class: "Class 10",
    section: "Section A",
    gender: "Male",
    status: "Active",
    dateOfJoin: "14 Oct, 2020",
    dob: "17 Nov, 2007",
  },
  {
    grNo: "111",
    name: "Devon Lane",
    rollNo: "S270111",
    class: "Class 1",
    section: "Section B",
    gender: "Male",
    status: "Inactive",
    dateOfJoin: "21 Nov, 2020",
    dob: "13 Jun, 2015",
  },
  {
    grNo: "112",
    name: "Annette Black",
    rollNo: "S270112",
    class: "Class 2",
    section: "Section C",
    gender: "Female",
    status: "Active",
    dateOfJoin: "18 Dec, 2020",
    dob: "5 Sep, 2014",
  },
  {
    grNo: "113",
    name: "Jerome Bell",
    rollNo: "S270113",
    class: "Class 3",
    section: "Section A",
    gender: "Male",
    status: "Active",
    dateOfJoin: "10 Jan, 2021",
    dob: "2 Feb, 2013",
  },
  {
    grNo: "114",
    name: "Leslie Alexander",
    rollNo: "S270114",
    class: "Class 4",
    section: "Section B",
    gender: "Female",
    status: "Inactive",
    dateOfJoin: "6 Feb, 2021",
    dob: "9 Nov, 2012",
  },
  {
    grNo: "115",
    name: "Wade Warren",
    rollNo: "S270115",
    class: "Class 5",
    section: "Section C",
    gender: "Male",
    status: "Active",
    dateOfJoin: "15 Mar, 2021",
    dob: "25 Mar, 2011",
  },
  {
    grNo: "116",
    name: "Kristin Watson",
    rollNo: "S270116",
    class: "Class 6",
    section: "Section A",
    gender: "Female",
    status: "Active",
    dateOfJoin: "7 Apr, 2021",
    dob: "14 May, 2010",
  },
  {
    grNo: "117",
    name: "Jenny Wilson",
    rollNo: "S270117",
    class: "Class 7",
    section: "Section B",
    gender: "Female",
    status: "Inactive",
    dateOfJoin: "19 May, 2021",
    dob: "1 Jan, 2009",
  },
  {
    grNo: "118",
    name: "Albert Flores",
    rollNo: "S270118",
    class: "Class 8",
    section: "Section C",
    gender: "Male",
    status: "Active",
    dateOfJoin: "30 Jun, 2021",
    dob: "3 Aug, 2008",
  },
  {
    grNo: "119",
    name: "Kathryn Murphy",
    rollNo: "S270119",
    class: "Class 9",
    section: "Section A",
    gender: "Female",
    status: "Active",
    dateOfJoin: "9 Jul, 2021",
    dob: "18 Dec, 2007",
  },
  {
    grNo: "120",
    name: "Floyd Miles",
    rollNo: "S270120",
    class: "Class 10",
    section: "Section B",
    gender: "Male",
    status: "Inactive",
    dateOfJoin: "21 Aug, 2021",
    dob: "12 Mar, 2006",
  },
  {
    grNo: "121",
    name: "Savannah Nguyen",
    rollNo: "S270121",
    class: "Class 1",
    section: "Section C",
    gender: "Female",
    status: "Active",
    dateOfJoin: "1 Sep, 2021",
    dob: "5 Oct, 2015",
  },
  {
    grNo: "122",
    name: "Esther Howard",
    rollNo: "S270122",
    class: "Class 2",
    section: "Section A",
    gender: "Female",
    status: "Inactive",
    dateOfJoin: "18 Oct, 2021",
    dob: "6 Jun, 2014",
  },
  {
    grNo: "123",
    name: "Bessie Cooper",
    rollNo: "S270123",
    class: "Class 3",
    section: "Section B",
    gender: "Female",
    status: "Active",
    dateOfJoin: "25 Nov, 2021",
    dob: "29 Apr, 2013",
  },
  {
    grNo: "124",
    name: "Ronald Richards",
    rollNo: "S270124",
    class: "Class 4",
    section: "Section C",
    gender: "Male",
    status: "Active",
    dateOfJoin: "3 Dec, 2021",
    dob: "8 Feb, 2012",
  },
  {
    grNo: "125",
    name: "Cameron Williamson",
    rollNo: "S270125",
    class: "Class 5",
    section: "Section A",
    gender: "Male",
    status: "Inactive",
    dateOfJoin: "14 Jan, 2022",
    dob: "16 May, 2011",
  },
  {
    grNo: "126",
    name: "Brooklyn Simmons",
    rollNo: "S270126",
    class: "Class 6",
    section: "Section B",
    gender: "Female",
    status: "Active",
    dateOfJoin: "27 Feb, 2022",
    dob: "3 Jul, 2010",
  },
  {
    grNo: "127",
    name: "Evan Rogers",
    rollNo: "S270127",
    class: "Class 7",
    section: "Section C",
    gender: "Male",
    status: "Active",
    dateOfJoin: "6 Mar, 2022",
    dob: "7 Oct, 2009",
  },
  {
    grNo: "128",
    name: "Sophia Turner",
    rollNo: "S270128",
    class: "Class 8",
    section: "Section A",
    gender: "Female",
    status: "Inactive",
    dateOfJoin: "22 Apr, 2022",
    dob: "21 Aug, 2008",
  },
  {
    grNo: "129",
    name: "Alexander Gray",
    rollNo: "S270129",
    class: "Class 9",
    section: "Section B",
    gender: "Male",
    status: "Active",
    dateOfJoin: "5 May, 2022",
    dob: "19 Sep, 2007",
  },
  {
    grNo: "130",
    name: "Amelia Harris",
    rollNo: "S270130",
    class: "Class 10",
    section: "Section C",
    gender: "Female",
    status: "Active",
    dateOfJoin: "17 Jun, 2022",
    dob: "10 Jan, 2006",
  },
  {
    grNo: "131",
    name: "Benjamin Lewis",
    rollNo: "S270131",
    class: "Class 1",
    section: "Section A",
    gender: "Male",
    status: "Inactive",
    dateOfJoin: "9 Jul, 2022",
    dob: "15 Dec, 2015",
  },
  {
    grNo: "132",
    name: "Chloe Martin",
    rollNo: "S270132",
    class: "Class 2",
    section: "Section B",
    gender: "Female",
    status: "Active",
    dateOfJoin: "1 Aug, 2022",
    dob: "8 Mar, 2014",
  },
  {
    grNo: "133",
    name: "Daniel Scott",
    rollNo: "S270133",
    class: "Class 3",
    section: "Section C",
    gender: "Male",
    status: "Active",
    dateOfJoin: "20 Sep, 2022",
    dob: "25 Oct, 2013",
  },
  {
    grNo: "134",
    name: "Emily King",
    rollNo: "S270134",
    class: "Class 4",
    section: "Section A",
    gender: "Female",
    status: "Inactive",
    dateOfJoin: "4 Oct, 2022",
    dob: "30 May, 2012",
  },
  {
    grNo: "135",
    name: "Henry Adams",
    rollNo: "S270135",
    class: "Class 5",
    section: "Section B",
    gender: "Male",
    status: "Active",
    dateOfJoin: "12 Nov, 2022",
    dob: "14 Apr, 2011",
  },
  {
    grNo: "136",
    name: "Isabella Nelson",
    rollNo: "S270136",
    class: "Class 6",
    section: "Section C",
    gender: "Female",
    status: "Active",
    dateOfJoin: "7 Dec, 2022",
    dob: "22 Feb, 2010",
  },
  {
    grNo: "137",
    name: "Jack Carter",
    rollNo: "S270137",
    class: "Class 7",
    section: "Section A",
    gender: "Male",
    status: "Inactive",
    dateOfJoin: "18 Jan, 2023",
    dob: "9 Jun, 2009",
  },
  {
    grNo: "138",
    name: "Lily Mitchell",
    rollNo: "S270138",
    class: "Class 8",
    section: "Section B",
    gender: "Female",
    status: "Active",
    dateOfJoin: "2 Feb, 2023",
    dob: "11 Aug, 2008",
  },
  {
    grNo: "139",
    name: "Matthew Perez",
    rollNo: "S270139",
    class: "Class 9",
    section: "Section C",
    gender: "Male",
    status: "Active",
    dateOfJoin: "16 Mar, 2023",
    dob: "27 Jul, 2007",
  },
  {
    grNo: "140",
    name: "Olivia Ross",
    rollNo: "S270140",
    class: "Class 10",
    section: "Section A",
    gender: "Female",
    status: "Inactive",
    dateOfJoin: "29 Apr, 2023",
    dob: "5 Oct, 2006",
  },
  
];

export default students;
