const teachers = [
  {
    id: 816,
    name: "Jacob Jones",
    class: "2nd Class - F",
    subject: "Python Tutors",
    phone: "+91 9123456780",
    email: "jacob.jones@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Active",
  },
  {
    id: 556,
    name: "Eleanor Pena",
    class: "2nd Class - E",
    subject: "SAT Tutors",
    phone: "+91 9123456781",
    email: "eleanor.pena@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Inactive",
  },
  {
    id: 583,
    name: "Jane Cooper",
    class: "2nd Class - G",
    subject: "Writing Tutors",
    phone: "+91 9123456782",
    email: "jane.cooper@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Active",
  },
  {
    id: 426,
    name: "Arlene McCoy",
    class: "2nd Class - C",
    subject: "ACT Tutors",
    phone: "+91 9123456783",
    email: "arlene.mccoy@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Active",
  },
  {
    id: 647,
    name: "Cameron Williamson",
    class: "2nd Class - D",
    subject: "SHSAT Tutors",
    phone: "+91 9123456784",
    email: "cameron.williamson@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Inactive",
  },
  {
    id: 600,
    name: "Leslie Alexander",
    class: "2nd Class - E",
    subject: "Physics Tutors",
    phone: "+91 9123456785",
    email: "leslie.alexander@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Active",
  },
  {
    id: 740,
    name: "Dianne Russell",
    class: "2nd Class - H",
    subject: "Algebra Tutors",
    phone: "+91 9123456786",
    email: "dianne.russell@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Active",
  },
  {
    id: 826,
    name: "Ronald Richards",
    class: "2nd Class - G",
    subject: "Chemistry Tutors",
    phone: "+91 9123456787",
    email: "ronald.richards@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Inactive",
  },
  {
    id: 274,
    name: "Theresa Webb",
    class: "2nd Class - A",
    subject: "Math Tutors",
    phone: "+91 9123456788",
    email: "theresa.webb@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Active",
  },
  {
    id: 196,
    name: "Esther Howard",
    class: "2nd Class - D",
    subject: "Algebra Tutors",
    phone: "+91 9123456789",
    email: "esther.howard@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Active",
  },
  {
    id: 877,
    name: "Cody Fisher",
    class: "2nd Class - I",
    subject: "English Tutors",
    phone: "+91 9123456790",
    email: "cody.fisher@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Active",
  },
  {
    id: 447,
    name: "Albert Flores",
    class: "2nd Class - H",
    subject: "Calculus Tutors",
    phone: "+91 9123456791",
    email: "albert.flores@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Active",
  },
  {
    id: 154,
    name: "Darlene Robertson",
    class: "2nd Class - A",
    subject: "Statistics Tutors",
    phone: "+91 9123456792",
    email: "darlene.robertson@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Inactive",
  },
  {
    id: 492,
    name: "Robert Fox",
    class: "2nd Class - H",
    subject: "Spanish Tutors",
    phone: "+91 9123456793",
    email: "robert.fox@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Active",
  },
  {
    id: 703,
    name: "Jenny Wilson",
    class: "2nd Class - H",
    subject: "Coding Tutors",
    phone: "+91 9123456794",
    email: "jenny.wilson@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Active",
  },
  {
    id: 798,
    name: "Bessie Cooper",
    class: "2nd Class - B",
    subject: "ESL Tutors",
    phone: "+91 9123456795",
    email: "bessie.cooper@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Active",
  },
  {
    id: 561,
    name: "Wade Warren",
    class: "2nd Class - E",
    subject: "Reading Tutors",
    phone: "+91 9123456796",
    email: "wade.warren@example.com",
    dateOfJoin: "1 Feb, 2025",
    status: "Inactive",
  },
  // ---- Add 23 more (19–40) ----
];

export default teachers;